---

- name: Install base packages
  ansible.builtin.package:
    name:
      - acl
      - gnupg2
    state: present
    update_cache: yes

- name: Include nftables tasks
  import_tasks: nftables.yml

- name: Include resolvconf tasks
  import_tasks: resolvconf.yml

- name: Include journal_storage tasks
  import_tasks: journal_storage.yml
