---

# Run nsd and unbound on the same server(s) - usually not recommended
nsd_interfaces:
  - 127.0.0.1@5353

nsd_zones:
  - name: lab.internal
    soa: lab01.lab.internal
    serial: 1
    name_servers:
      - lab01
      - lab02
    records:
      - name: lab01
        content: 192.168.123.11
      - name: lab02
        content: 192.168.123.12
      - name: lab03
        content: 192.168.123.13
      - name: db
        content: 192.168.123.13
  - name: 123.168.192.in-addr.arpa
    soa: lab01.lab.internal
    serial: 1
    name_servers:
      - lab01
      - lab02
    records:
      - name: 11
        type: PTR
        content: lab01.lab.internal.
      - name: 12
        type: PTR
        content: lab02.lab.internal.
      - name: 13
        type: PTR
        content: lab03.lab.internal.

unbound_interfaces:
  - 0.0.0.0

# Allow queries to localhost
unbound_do_not_query_localhost: false

# Ignore DNSSEC
unbound_insecure_domains:
  - lab.internal

# Required for reverse DNS in our private address range
unbound_local_zones:
  - name: 168.192.in-addr.arpa
    type: nodefault

unbound_access_control:
  - netblock: 192.168.123.0/24
    action: allow

unbound_stub_zones:
  - name: lab.internal
    servers:
      - 127.0.0.1@5353
  - name: 123.168.192.in-addr.arpa
    servers:
      - 127.0.0.1@5353
