---

nftables_input_tcp: [53]
nftables_input_udp: [53]

unbound_interfaces:
  - 0.0.0.0

# Ignore DNSSEC
unbound_insecure_domains:
  - lab.internal

# Required for reverse DNS in our private address range
unbound_local_zones:
  - name: 168.192.in-addr.arpa
    type: nodefault

unbound_access_control:
  - netblock: 192.168.123.0/24
    action: allow

unbound_stub_zones:
  - name: lab.internal
    servers:
      - 192.168.123.11
      - 192.168.123.12
  - name: 123.168.192.in-addr.arpa
    servers:
      - 192.168.123.11
      - 192.168.123.12
