---

- hosts: all
  roles:
    - common

- hosts: nameservers
  roles:
    - nsd
    - unbound

- hosts: saltmasters
  roles:
    - salt-master

- hosts: logging
  roles:
    - journal-remote

- hosts: dbservers
  roles:
    - postgresql

- hosts: monitoring
  roles:
    - zabbix-server
    - zabbix-web

- hosts: gitservers
  roles:
    - gitea

- hosts: all
  roles:
    - salt-minion
    - zabbix-agent

- hosts: all:!logging
  roles:
    - journal-upload
