---

- hosts: all
  roles:
    - common
    - zabbix-agent

- hosts: nameservers
  roles:
    - nsd
    - unbound

- hosts: dbservers
  roles:
    - postgresql

- hosts: monitoring
  roles:
    - zabbix-server
    - zabbix-web
